### ISSUE TITLE
Church has been written as Chuch in three places

### ISSUE THREAD

**Issue by gryffydd** [lucasoshiro/lambdasort#1]
A beautiful read - Thanks heaps for the comprehensive explanation

Church has been written as Chuch in three places in the README.md.

There is also a 'Luckly', which I assume should be 'Luckily' by context.

I apologise if this issue is unwanted.

**Comment by lucasoshiro** [comment]
Thanks @gryffydd ! And forgive me for only answering you now...

Fixed: e9785401f39295be19aa39d43efdac2918d7c6fa

PS: I'm happy that you liked it!
